name: Sync dev with main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev

      - name: Sync dev with main
        run: |
          git config pull.rebase false
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout dev
          git pull origin main
          git push origin dev
